#! /bin/bash
############################################################################
#
# Copyright (c) 2014 - rexfordnyrk (rexfordnyrk@gmail.com)
#
# This script file is intended for Student Management Software Project
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################
reset;


Modify()
{
while :
do
	echo "		Please Enter The StudentID To Modify Or Make Changes To"
	echo
	echo
	read StudentID


	FileDir=Studentfiles/Student_Info
	error_found=0

	if [ ! -e $FileDir.$StudentID ]
	  then
	    echo "		Error: StudentID '$StudentID' does not exist"
	    echo "				Or Is Incorrect"
	    error_found=1
	fi


	if [ $error_found == 1 ]
	then
	  echo
	  echo "		Ensure You Have Entered The Correct StudentID "
	fi

	if [ -e $FileDir.$StudentID ]
	  then 
	    clear
	    echo
	    cd $PWD/Studentfiles
	    vi "Student_Info.$StudentID";
	    echo "		Done Modifying	"
	    break;
	fi

	scripts/press_enter
done
}
Modify
