#! /bin/bash
############################################################################
#
# Copyright (c) 2014 - rexfordnyrk (rexfordnyrk@gmail.com)
#
# This script file is intended for Student Management Software Project
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################
reset;
StudentIdSearch()
{
while :
do
	echo "		Please Enter The StudentID Of the Student To Search"
	echo
	echo
	read StudentID


	FileDir=Studentfiles/Student_Info
	error_found=0

	if [ ! -e $FileDir.$StudentID ]
	  then
	    echo "		Error: StudentID '$StudentID' does not exist"
	    echo "				Or Is Incorrect"
	    error_found=1
	fi


	if [ $error_found == 1 ]
	then
	  echo
	  echo "		Ensure You Have Entered The Correct StudentID "
	fi

	if [ -e $FileDir.$StudentID ]
	  then 
	    clear
	    echo
	    echo "		Here Are The Student Details For StudentID $StudentID		"
	    cd $PWD/Studentfiles
	    cat < "Student_Info.$StudentID";
	    break;
	fi

	scripts/press_enter
done
}
StudentIdSearch
