#! /bin/bash
############################################################################
#
# Copyright (c) 2014 - rexfordnyrk (rexfordnyrk@gmail.com)
#
# This script file is intended for Student Management Software Project
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################
reset;

Search_Option()
{
while :
do

  clear

  echo 
  echo "================================================================="
  echo " Student Management Software- by rexfordnyrk (@rexfordnyrk)"
  echo "================================================================="
  echo 
  echo ">>>>>>>>>>>>>>>>>>>>>>> SEARCH OPTIONS <<<<<<<<<<<<<<<<<<<<<<<<<<"
  echo
  echo "  		1 - 	Search By Student_ID"
  echo "  		2 - 	Search By Stream-Wise and Semister-Wise"
  echo "  		3 - 	Search By City-Wise"
  echo "  		4 - 	Search By State-Wise"
  echo 
  echo "  		x - 	Return to Main Menu"
  echo
  echo 
  echo -n "Enter option: "
  read opt

  if [ "$?" != "1" ]
  then
      case $opt in
      1) scripts/SearchByStudentID;;
      2) scripts/SearchByStreamwise;;
      3) scripts/SearchByCitywise;;
      4) scripts/SearchByStatewise;;
      x) exit ;;
      *) echo "Invalid option";;
    esac
  fi

  scripts/press_enter
done
}
Search_Option
